name:                mstates
version:             0.1.0.0
github:              "smunix/mstates"
license:             BSD3
author:              "Providence Salumu"
maintainer:          "Providence.Salumu@smunix.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smunix/mstates#readme>

library:
  source-dirs: src
  exposed-modules:
  - Data.String.Strip
  dependencies:
  - base >=4.7 && <5
executables:
  mstates:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - mtl
    - text
    - transformers
    - mstates
    default-extensions:
    - DataKinds
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - OverloadedStrings
    - ViewPatterns

tests:
  mstates-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - mstates
    - hspec
    - QuickCheck
